modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "mtrsteamloco"
version = "${version}"
displayName = "MTR Steam Locomotive Addon"
authors = "Zbx1425"
description = "Steam locomotive extension for the Minecraft Transit Railway mod"
logoFile = "icon.png"

[[dependencies.mtrsteamloco]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtrsteamloco]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtrsteamloco]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mtrsteamloco]]
modId = "mtr"
mandatory = true
versionRange = "1.0"
ordering = "AFTER"
side = "BOTH"
